export const bucketListData = [
  {
      title: "Cherry Blossom Season",
      location: "Kyoto, Japan",
      description: "Witness sakura bloom at historic temples and gardens",
      slug: "cherry-blossom-season",
      checked: false,
  },
  {
      title: "Northern Lights Experience",
      location: "Tromsø, Norway & Reykjavik, Iceland",
      description: "Chase the aurora borealis in Arctic regions",
      slug: "northern-lights-experience",
      checked: false,
  },
  {
      title: "African Safari Adventure",
      location: "Multiple Locations, Africa",
      description: "Experience wildlife in Serengeti, Maasai Mara, Kruger Park, and Botswana",
      slug: "african-safari-adventure",
      checked: true,
  },
  {
      title: "Great Barrier Reef Experience",
      location: "Queensland, Australia",
      description: "Explore the reef through diving, snorkeling, sailing, and aerial tours",
      slug: "great-barrier-reef-experience",
      checked: true,
  },
  {
      title: "Machu Picchu Trek",
      location: "Cusco Region, Peru",
      description: "Hike the Inca Trail to the ancient citadel of Machu Picchu",
      slug: "machu-picchu-trek",
      checked: false,
  },
  {
      title: "Greek Islands Experience",
      location: "Santorini & Other Islands, Greece",
      description: "Explore Santorini's caldera, sunsets, wine culture, and boat tours",
      slug: "greek-islands-experience",
      checked: false,
  },
  {
      title: "Patagonia Adventure",
      location: "Chile & Argentina",
      description: "Trek through the stunning landscapes of Patagonia's national parks",
      slug: "patagonia-adventure",
      checked: false,
  },
  {
      title: "Swiss Alps Experience",
      location: "Switzerland",
      description: "Explore the Alps through hiking, skiing, scenic trains, and chocolate tours",
      slug: "swiss-alps-experience",
      checked: false,
  },
  {
      title: "Great Wall of China Experience",
      location: "Beijing, China",
      description: "Explore various sections, including hiking and marathon options",
      slug: "great-wall-experience",
      checked: true,
  },
  {
      title: "Paris Cultural Tour",
      location: "Paris, France",
      description: "Visit iconic sites including Eiffel Tower, Louvre, Seine River, and Montmartre",
      slug: "paris-cultural-tour",
      checked: true,
  },
  {
      title: "US National Parks Tour",
      location: "United States",
      description: "Explore Grand Canyon, Yellowstone, Grand Teton, and Great Smoky Mountains",
      slug: "us-national-parks-tour",
      checked: false,
  },
  {
      title: "Bali Island Experience",
      location: "Bali, Indonesia",
      description: "Explore beaches, rice terraces, temples, and monkey forests",
      slug: "bali-island-experience",
      checked: true,
  },
  {
      title: "Italian Cities Tour",
      location: "Italy",
      description: "Experience Venice, Rome, and Cinque Terre's unique attractions",
      slug: "italian-cities-tour",
      checked: false,
  },
  {
      title: "Australian Landmarks Tour",
      location: "Australia",
      description: "Visit Sydney Opera House, Great Ocean Road, and other iconic sites",
      slug: "australian-landmarks-tour",
      checked: true,
  },
  {
      title: "Cappadocia Adventure",
      location: "Cappadocia, Turkey",
      description: "Experience hot air balloons, cave hotels, and underground cities",
      slug: "cappadocia-adventure",
      checked: false,
  },
  {
      title: "Galápagos Islands Expedition",
      location: "Galápagos Islands, Ecuador",
      description: "Explore unique wildlife and ecosystems through tours and adventures",
      slug: "galapagos-expedition",
      checked: false,
  },
  {
      title: "Canadian Rockies Experience",
      location: "Banff & Lake Louise, Canada",
      description: "Explore through hiking, gondola rides, and lake activities",
      slug: "canadian-rockies-experience",
      checked: false,
  },
  {
      title: "Dubai Modern Marvels",
      location: "Dubai, UAE",
      description: "Experience desert safaris, modern architecture, and luxury attractions",
      slug: "dubai-modern-marvels",
      checked: false,
  },
  {
      title: "Morocco Cultural Journey",
      location: "Morocco",
      description: "Explore Marrakech medina, Sahara Desert, and authentic experiences",
      slug: "morocco-cultural-journey",
      checked: false,
  },
  {
      title: "Brazilian Carnival & Amazon",
      location: "Brazil",
      description: "Experience Rio Carnival and explore the Amazon rainforest",
      slug: "brazilian-carnival-amazon",
      checked: false,
  },
  {
      title: "Historic UK Tour",
      location: "United Kingdom",
      description: "Visit Stonehenge and other historic sites across Britain",
      slug: "historic-uk-tour",
      checked: false,
  },
  {
      title: "Jordan & Petra Experience",
      location: "Jordan",
      description: "Explore Petra by day and night, plus Dead Sea floating",
      slug: "jordan-petra-experience",
      checked: false,
  },
  {
      title: "Egypt Pyramids & Nile",
      location: "Egypt",
      description: "Explore the pyramids and cruise down the Nile River",
      slug: "egypt-pyramids-nile",
      checked: false,
  },
  {
      title: "India Golden Triangle",
      location: "India",
      description: "Visit Delhi, Agra (Taj Mahal), and Jaipur's iconic sites",
      slug: "india-golden-triangle",
      checked: false,
  },
  {
      title: "Iceland Ring Road Journey",
      location: "Iceland",
      description: "Experience Golden Circle, Blue Lagoon, glaciers, and Ring Road",
      slug: "iceland-ring-road",
      checked: false,
  },
  {
      title: "Japanese Culture Immersion",
      location: "Japan",
      description: "Experience Tokyo, Mount Fuji, and Kyoto's cultural sites",
      slug: "japanese-culture-immersion",
      checked: true,
  },
  {
      title: "Maldives Overwater Experience",
      location: "Maldives",
      description: "Stay in overwater villas and explore marine life",
      slug: "maldives-overwater-experience",
      checked: false,
  },
  {
      title: "Antarctica Expedition",
      location: "Antarctica",
      description: "Journey to the white continent and witness polar wildlife",
      slug: "antarctica-expedition",
      checked: false,
  },
  {
      title: "Croatian Coast Adventure",
      location: "Croatia",
      description: "Explore Dubrovnik's walls and island hop along the Dalmatian Coast",
      slug: "croatian-coast-adventure",
      checked: true,
  },
  {
      title: "New Zealand Adventure",
      location: "New Zealand",
      description: "Experience Lord of the Rings locations and adventure sports",
      slug: "new-zealand-adventure",
      checked: false,
  },
  {
      title: "Turkish Bath Experience",
      location: "Istanbul, Turkey",
      description: "Visit a traditional hammam and explore the Hagia Sophia",
      slug: "turkish-bath-experience",
      checked: false,
  },
  {
      title: "Portuguese Food & Culture",
      location: "Portugal",
      description: "Experience Lisbon's trams, Porto's wine, and Fado music",
      slug: "portuguese-food-culture",
      checked: true,
  },
  {
      title: "Vietnam Street Food Tour",
      location: "Vietnam",
      description: "Sample local cuisine and explore ancient towns",
      slug: "vietnam-street-food-tour",
      checked: false,
  },
  {
      title: "Spanish Flamenco & Tapas",
      location: "Spain",
      description: "Experience Barcelona's architecture and authentic flamenco shows",
      slug: "spanish-flamenco-tapas",
      checked: true,
  },
  {
      title: "Scottish Highlands Tour",
      location: "Scotland",
      description: "Explore castles, lochs, and whisky distilleries",
      slug: "scottish-highlands-tour",
      checked: false,
  },
  {
      title: "South African Wine Tour",
      location: "South Africa",
      description: "Visit Cape Town vineyards and coastal penguin colonies",
      slug: "south-african-wine-tour",
      checked: true,
  },
  {
      title: "Finnish Lapland Winter",
      location: "Finland",
      description: "Stay in glass igloos and visit Santa's village",
      slug: "finnish-lapland-winter",
      checked: false,
  },
  {
      title: "Mexican Pyramid Tour",
      location: "Mexico",
      description: "Explore ancient Mayan and Aztec pyramids",
      slug: "mexican-pyramid-tour",
      checked: false,
  },
  {
      title: "Cambodian Temples",
      location: "Cambodia",
      description: "Explore Angkor Wat and other ancient temples",
      slug: "cambodian-temples",
      checked: false,
  },
  {
      title: "Trans-Siberian Railway",
      location: "Russia",
      description: "Journey across Russia by legendary railway",
      slug: "trans-siberian-railway",
      checked: false,
  },
  {
      title: "Irish Pub & Castle Tour",
      location: "Ireland",
      description: "Visit historic pubs and stay in castle hotels",
      slug: "irish-pub-castle-tour",
      checked: false,
  },
  {
      title: "Bhutan Buddhist Experience",
      location: "Bhutan",
      description: "Visit Tiger's Nest Monastery and experience Buddhist culture",
      slug: "bhutan-buddhist-experience",
      checked: false,
  },
  {
      title: "Madagascar Wildlife Tour",
      location: "Madagascar",
      description: "Spot unique lemurs and baobab trees",
      slug: "madagascar-wildlife-tour",
      checked: false,
  },
  {
      title: "Inca Trail Alternative",
      location: "Peru",
      description: "Hike the Salkantay Trek to Machu Picchu",
      slug: "inca-trail-alternative",
      checked: false,
  },
  {
      title: "Mongolia Nomad Life",
      location: "Mongolia",
      description: "Stay in ger camps and experience nomadic culture",
      slug: "mongolia-nomad-life",
      checked: false,
  },
  {
      title: "Namibia Desert Safari",
      location: "Namibia",
      description: "Explore red dunes and spot desert-adapted wildlife",
      slug: "namibia-desert-safari",
      checked: false,
  },
  {
      title: "Colombian Coffee Tour",
      location: "Colombia",
      description: "Visit coffee plantations and colonial towns",
      slug: "colombian-coffee-tour",
      checked: false,
  },
  {
      title: "Greek Mythology Tour",
      location: "Greece",
      description: "Explore ancient sites and mythological locations",
      slug: "greek-mythology-tour",
      checked: false,
  },
  {
      title: "Norwegian Fjords Cruise",
      location: "Norway",
      description: "Sail through dramatic fjords and coastal villages",
      slug: "norwegian-fjords-cruise",
      checked: false,
  },
  {
      title: "Silk Road Journey",
      location: "Central Asia",
      description: "Travel ancient trade routes through multiple countries",
      slug: "silk-road-journey",
      checked: false,
  },
  {
      title: "Hawaii Volcano Tour",
      location: "Hawaii, USA",
      description: "Witness active volcanoes and tropical beaches",
      slug: "hawaii-volcano-tour",
      checked: false,
  },
  {
    title: "Petra Night Experience",
    location: "Petra, Jordan",
    description: "Walk through the candlelit Siq to the Treasury",
    slug: "petra-night-experience",
    checked: false,
},
{
    title: "Easter Island Statues",
    location: "Easter Island, Chile",
    description: "Explore the mysterious moai statues and their history",
    slug: "easter-island-statues",
    checked: true,
},
{
    title: "Tibet Monastery Tour",
    location: "Tibet",
    description: "Visit ancient Buddhist monasteries and Mount Everest Base Camp",
    slug: "tibet-monastery-tour",
    checked: false,
},
{
    title: "Greenland Ice Sheet",
    location: "Greenland",
    description: "Witness the massive ice sheet and stay in an Inuit village",
    slug: "greenland-ice-sheet",
    checked: false,
},
{
    title: "Sri Lankan Tea Country",
    location: "Sri Lanka",
    description: "Ride scenic trains through tea plantations and colonial towns",
    slug: "sri-lankan-tea-country",
    checked: false,
},
{
    title: "Rajasthan Palace Stay",
    location: "Rajasthan, India",
    description: "Experience royal luxury in converted palace hotels",
    slug: "rajasthan-palace-stay",
    checked: false,
},
{
    title: "Slovenia Lake Tour",
    location: "Slovenia",
    description: "Visit Lake Bled and explore underground caves",
    slug: "slovenia-lake-tour",
    checked: false,
},
{
    title: "Atacama Desert Stargazing",
    location: "Chile",
    description: "Stargaze in the world's driest desert",
    slug: "atacama-desert-stargazing",
    checked: false,
},
{
    title: "Romanian Castle Tour",
    location: "Romania",
    description: "Explore Transylvania's gothic castles and medieval towns",
    slug: "romanian-castle-tour",
    checked: false,
},
{
    title: "Myanmar Temple Run",
    location: "Myanmar",
    description: "Explore thousands of temples in Bagan by e-bike",
    slug: "myanmar-temple-run",
    checked: false,
},
{
    title: "Faroe Islands Hiking",
    location: "Faroe Islands",
    description: "Hike dramatic cliffs and visit puffin colonies",
    slug: "faroe-islands-hiking",
    checked: false,
},
{
    title: "Caucasus Wine Tour",
    location: "Georgia",
    description: "Experience the world's oldest wine culture",
    slug: "caucasus-wine-tour",
    checked: false,
},
{
    title: "Palestinian Food Tour",
    location: "West Bank",
    description: "Experience traditional Palestinian cuisine and culture",
    slug: "palestinian-food-tour",
    checked: false,
},
{
    title: "Albanian Riviera",
    location: "Albania",
    description: "Explore untouched beaches and ancient ruins",
    slug: "albanian-riviera",
    checked: false,
},
{
    title: "Svalbard Polar Bears",
    location: "Svalbard, Norway",
    description: "Spot polar bears in the high Arctic",
    slug: "svalbard-polar-bears",
    checked: false,
},
{
    title: "Komodo Dragon Trek",
    location: "Indonesia",
    description: "See Komodo dragons in their natural habitat",
    slug: "komodo-dragon-trek",
    checked: false,
},
{
    title: "Kazakhstan Space Port",
    location: "Kazakhstan",
    description: "Visit the Baikonur Cosmodrome space launch facility",
    slug: "kazakhstan-space-port",
    checked: false,
},
{
    title: "Ethiopian Rock Churches",
    location: "Ethiopia",
    description: "Explore ancient rock-hewn churches of Lalibela",
    slug: "ethiopian-rock-churches",
    checked: false,
},
{
    title: "Omani Desert Camp",
    location: "Oman",
    description: "Stay in luxury desert camps and explore wadis",
    slug: "omani-desert-camp",
    checked: false,
},
{
    title: "Orkney Ancient Sites",
    location: "Scotland",
    description: "Visit Neolithic sites older than the pyramids",
    slug: "orkney-ancient-sites",
    checked: false,
},
{
    title: "Armenian Monasteries",
    location: "Armenia",
    description: "Explore ancient Christian monasteries in dramatic locations",
    slug: "armenian-monasteries",
    checked: false,
},
{
    title: "Uzbek Silk Road Cities",
    location: "Uzbekistan",
    description: "Visit the ancient cities of Samarkand and Bukhara",
    slug: "uzbek-silk-road-cities",
    checked: false,
},
{
    title: "Beirut Food Scene",
    location: "Lebanon",
    description: "Experience the vibrant Lebanese culinary culture",
    slug: "beirut-food-scene",
    checked: false,
},
{
    title: "Slovenian Wine Route",
    location: "Slovenia",
    description: "Tour family wineries and historic cellar doors",
    slug: "slovenian-wine-route",
    checked: true,
},
{
    title: "Transylvanian Villages",
    location: "Romania",
    description: "Experience traditional village life and folk culture",
    slug: "transylvanian-villages",
    checked: false,
},
{
    title: "Lofoten Islands",
    location: "Norway",
    description: "Photography tour of dramatic Arctic landscapes",
    slug: "lofoten-islands",
    checked: false,
},
{
    title: "Cyprus Beach Hopping",
    location: "Cyprus",
    description: "Explore ancient ruins and crystal-clear beaches",
    slug: "cyprus-beach-hopping",
    checked: false,
},
{
    title: "Luxembourg Castles",
    location: "Luxembourg",
    description: "Tour the fairy-tale castles of the tiny duchy",
    slug: "luxembourg-castles",
    checked: false,
},
{
    title: "Macedonian Lakes",
    location: "North Macedonia",
    description: "Visit historic lakeside monasteries and towns",
    slug: "macedonian-lakes",
    checked: false,
},
{
    title: "Latvian Art Nouveau",
    location: "Riga, Latvia",
    description: "Explore Europe's art nouveau architectural capital",
    slug: "latvian-art-nouveau",
    checked: false,
},
{
    title: "Costa Rican Jungle",
    location: "Costa Rica",
    description: "Zipline through rainforest canopies and spot sloths",
    slug: "costa-rican-jungle",
    checked: false,
},
{
    title: "Maltese Heritage",
    location: "Malta",
    description: "Discover prehistoric temples and medieval cities",
    slug: "maltese-heritage",
    checked: false,
},
{
    title: "Lithuanian Hill of Crosses",
    location: "Lithuania",
    description: "Visit the mysterious hill covered in countless crosses",
    slug: "lithuanian-hill-crosses",
    checked: false,
},
{
    title: "Estonian Islands",
    location: "Estonia",
    description: "Explore traditional islands and Soviet remains",
    slug: "estonian-islands",
    checked: true,
},
{
    title: "Bolivian Salt Flats",
    location: "Bolivia",
    description: "Photography tour of the world's largest salt flat",
    slug: "bolivian-salt-flats",
    checked: false,
},
{
    title: "Palestinian Heritage",
    location: "Palestine",
    description: "Visit ancient olive groves and traditional markets",
    slug: "palestinian-heritage",
    checked: false,
},
{
    title: "Senegal Music Scene",
    location: "Senegal",
    description: "Experience vibrant West African music culture",
    slug: "senegal-music-scene",
    checked: false,
},
{
    title: "Belarus Time Capsule",
    location: "Belarus",
    description: "Explore Soviet-era architecture and pristine forests",
    slug: "belarus-time-capsule",
    checked: false,
},
{
    title: "Moldova Wine Caves",
    location: "Moldova",
    description: "Tour the world's largest wine cellar",
    slug: "moldova-wine-caves",
    checked: false,
},
{
    title: "Bangladeshi Rivers",
    location: "Bangladesh",
    description: "Cruise the Sundarbans mangrove forests",
    slug: "bangladeshi-rivers",
    checked: false,
},
{
    title: "Saskatchewan Northern Lights",
    location: "Canada",
    description: "Watch aurora borealis over pristine lakes",
    slug: "saskatchewan-northern-lights",
    checked: false,
},
{
    title: "Uruguayan Carnival",
    location: "Uruguay",
    description: "Experience the world's longest carnival",
    slug: "uruguayan-carnival",
    checked: false,
},
{
    title: "Nicaraguan Volcanoes",
    location: "Nicaragua",
    description: "Volcano boarding and crater lake swimming",
    slug: "nicaraguan-volcanoes",
    checked: false,
},
{
    title: "Mauritian Beaches",
    location: "Mauritius",
    description: "Explore pristine beaches and colonial heritage",
    slug: "mauritian-beaches",
    checked: true,
},
{
    title: "Bruneian Water Village",
    location: "Brunei",
    description: "Visit the world's largest water village",
    slug: "bruneian-water-village",
    checked: false,
},
{
    title: "Papua New Guinea Tribes",
    location: "Papua New Guinea",
    description: "Visit traditional tribes and sing-sing festivals",
    slug: "papua-new-guinea-tribes",
    checked: false,
},
{
    title: "Tajik Pamir Highway",
    location: "Tajikistan",
    description: "Road trip along one of the world's highest highways",
    slug: "tajik-pamir-highway",
    checked: false,
},
{
    title: "Kyrgyz Yurt Stay",
    location: "Kyrgyzstan",
    description: "Experience nomadic life in traditional yurts",
    slug: "kyrgyz-yurt-stay",
    checked: false,
},
{
    title: "Gabonese Wildlife",
    location: "Gabon",
    description: "Spot surfing hippos and lowland gorillas",
    slug: "gabonese-wildlife",
    checked: false,
},
{
    title: "Suriname River Tour",
    location: "Suriname",
    description: "Explore rainforest villages and Maroon culture",
    slug: "suriname-river-tour",
    checked: false,
},
{
    title: "Djibouti Lake Assal",
    location: "Djibouti",
    description: "Visit the lowest point in Africa",
    slug: "djibouti-lake-assal",
    checked: false,
}
];