// src/app/bucket-list/bucketListData.js

export const bucketListData = [
    {
      title: "Cherry Blossom Season",
      location: "Kyoto, Japan",
      description: "Witness sakura bloom at historic temples and gardens",
      slug: "cherry-blossom-season",
      checked: false,
    },
    {
      title: "Northern Lights in Iceland",
      location: "Tromsø, Norway",
      description: "Chase the aurora borealis in a glass igloo under the Arctic sky",
      slug: "northern-lights-in-iceland",
      checked: false,
    },
    {
      title: "Safari in Serengeti",
      location: "Serengeti National Park, Tanzania",
      description: "Experience the Great Migration and observe wildlife in their natural habitat",
      slug: "safari-in-serengeti",
      checked: false,
    },
    {
      title: "Great Barrier Reef Diving",
      location: "Queensland, Australia",
      description: "Dive into the vibrant underwater world of the Great Barrier Reef",
      slug: "great-barrier-reef-diving",
      checked: true, // Green Checkmark
    },
    {
      title: "Machu Picchu Trek",
      location: "Cusco Region, Peru",
      description: "Hike the Inca Trail to the ancient citadel of Machu Picchu",
      slug: "machu-picchu-trek",
      checked: false,
    },
    {
      title: "Santorini Sunset",
      location: "Santorini, Greece",
      description: "Enjoy breathtaking sunsets over the caldera in Santorini",
      slug: "santorini-sunset",
      checked: false,
    },
    {
      title: "Patagonia Hiking",
      location: "Torres del Paine, Chile",
      description: "Trek through the stunning landscapes of Patagonia's national parks",
      slug: "patagonia-hiking",
      checked: false,
    },
    {
      title: "Safari in Maasai Mara",
      location: "Maasai Mara, Kenya",
      description: "Witness the incredible wildlife and vibrant Maasai culture",
      slug: "safari-in-maasai-mara",
      checked: false,
    },
    {
      title: "Explore the Swiss Alps",
      location: "Zermatt, Switzerland",
      description: "Ski or hike in the picturesque Swiss Alps with views of the Matterhorn",
      slug: "explore-the-swiss-alps",
      checked: false,
    },
    {
      title: "Great Wall of China Trek",
      location: "Beijing, China",
      description: "Hike along the historic sections of the Great Wall",
      slug: "great-wall-of-china-trek",
      checked: true, // Green Checkmark
    },
    // ... Add 40 more items in the same format
    {
      title: "Eiffel Tower Visit",
      location: "Paris, France",
      description: "Experience the iconic Eiffel Tower and panoramic views of Paris",
      slug: "eiffel-tower-visit",
      checked: false,
    },
    {
      title: "Grand Canyon Exploration",
      location: "Arizona, USA",
      description: "Explore the vast and stunning landscapes of the Grand Canyon",
      slug: "grand-canyon-exploration",
      checked: false,
    },
    {
      title: "Bali Beach Relaxation",
      location: "Bali, Indonesia",
      description: "Relax on the pristine beaches and enjoy Bali's vibrant culture",
      slug: "bali-beach-relaxation",
      checked: false,
    },
    {
      title: "Venice Gondola Ride",
      location: "Venice, Italy",
      description: "Navigate the romantic canals of Venice on a traditional gondola",
      slug: "venice-gondola-ride",
      checked: false,
    },
    {
      title: "Sydney Opera House Tour",
      location: "Sydney, Australia",
      description: "Tour the architectural marvel of the Sydney Opera House",
      slug: "sydney-opera-house-tour",
      checked: false,
    },
    {
      title: "Great Ocean Road Drive",
      location: "Victoria, Australia",
      description: "Drive along the scenic Great Ocean Road with its stunning coastal views",
      slug: "great-ocean-road-drive",
      checked: false,
    },
    {
      title: "Cappadocia Balloon Ride",
      location: "Cappadocia, Turkey",
      description: "Take a hot air balloon ride over the unique landscapes of Cappadocia",
      slug: "cappadocia-balloon-ride",
      checked: false,
    },
    {
      title: "Antelope Canyon Visit",
      location: "Arizona, USA",
      description: "Marvel at the wave-like structure and light beams in Antelope Canyon",
      slug: "antelope-canyon-visit",
      checked: false,
    },
    {
      title: "Galápagos Islands Adventure",
      location: "Galápagos Islands, Ecuador",
      description: "Explore the unique wildlife and ecosystems of the Galápagos Islands",
      slug: "galapagos-islands-adventure",
      checked: false,
    },
    {
      title: "Safari in Botswana",
      location: "Botswana",
      description: "Experience unparalleled wildlife viewing in Botswana's national parks",
      slug: "safari-in-botswana",
      checked: false,
    },
    {
      title: "Tokyo City Tour",
      location: "Tokyo, Japan",
      description: "Immerse yourself in the bustling city life and cultural landmarks of Tokyo",
      slug: "tokyo-city-tour",
      checked: false,
    },
    {
      title: "Banff National Park Hiking",
      location: "Banff, Canada",
      description: "Hike through the stunning landscapes of Banff National Park",
      slug: "banff-national-park-hiking",
      checked: false,
    },
    {
      title: "Dubai Desert Safari",
      location: "Dubai, UAE",
      description: "Experience the thrill of dune bashing and traditional Bedouin culture",
      slug: "dubai-desert-safari",
      checked: false,
    },
    {
      title: "Marrakech Medina Exploration",
      location: "Marrakech, Morocco",
      description: "Wander through the vibrant souks and historic medina of Marrakech",
      slug: "marrakech-medina-exploration",
      checked: false,
    },
    {
      title: "Rio de Janeiro Carnival",
      location: "Rio de Janeiro, Brazil",
      description: "Participate in the world-famous Carnival celebrations in Rio",
      slug: "rio-de-janeiro-carnival",
      checked: false,
    },
    {
      title: "Stonehenge Visit",
      location: "Wiltshire, England",
      description: "Explore the ancient stone circle of Stonehenge and its mysteries",
      slug: "stonehenge-visit",
      checked: false,
    },
    {
      title: "Great Smoky Mountains Trek",
      location: "Tennessee/North Carolina, USA",
      description: "Hike through the lush trails of the Great Smoky Mountains",
      slug: "great-smoky-mountains-trek",
      checked: false,
    },
    {
      title: "Petra Archaeological Site",
      location: "Petra, Jordan",
      description: "Discover the ancient city carved into red sandstone cliffs",
      slug: "petra-archaeological-site",
      checked: false,
    },
    {
      title: "Banff Gondola Ride",
      location: "Banff, Canada",
      description: "Take a gondola ride for panoramic views of the Canadian Rockies",
      slug: "banff-gondola-ride",
      checked: false,
    },
    {
      title: "Taj Mahal Visit",
      location: "Agra, India",
      description: "Marvel at the stunning white marble mausoleum of the Taj Mahal",
      slug: "taj-mahal-visit",
      checked: false,
    },
    {
      title: "Cinque Terre Hiking",
      location: "Liguria, Italy",
      description: "Hike the scenic trails connecting the five colorful villages of Cinque Terre",
      slug: "cinque-terre-hiking",
      checked: false,
    },
    {
      title: "Banff Lake Louise Visit",
      location: "Lake Louise, Canada",
      description: "Visit the picturesque Lake Louise and its turquoise waters",
      slug: "lake-louise-visit",
      checked: false,
    },
    {
      title: "Hagia Sophia Tour",
      location: "Istanbul, Turkey",
      description: "Explore the historic Hagia Sophia with its rich history and architecture",
      slug: "hagia-sophia-tour",
      checked: false,
    },
    {
      title: "Safari in South Africa",
      location: "Kruger National Park, South Africa",
      description: "Experience diverse wildlife in one of Africa's largest game reserves",
      slug: "safari-in-south-africa",
      checked: false,
    },
    {
      title: "Alhambra Palace Visit",
      location: "Granada, Spain",
      description: "Tour the stunning Moorish palace and gardens of the Alhambra",
      slug: "alhambra-palace-visit",
      checked: false,
    },
    {
      title: "Yellowstone National Park",
      location: "Wyoming, USA",
      description: "Explore the geysers, hot springs, and diverse wildlife of Yellowstone",
      slug: "yellowstone-national-park",
      checked: false,
    },
    {
      title: "Louvre Museum Tour",
      location: "Paris, France",
      description: "Admire world-renowned art pieces, including the Mona Lisa, at the Louvre",
      slug: "louvre-museum-tour",
      checked: false,
    },
    {
      title: "Mount Fuji Climb",
      location: "Honshu, Japan",
      description: "Conquer Japan's tallest peak and enjoy stunning sunrise views",
      slug: "mount-fuji-climb",
      checked: false,
    },
    {
      title: "Great Barrier Reef Snorkeling",
      location: "Queensland, Australia",
      description: "Snorkel among vibrant coral reefs and diverse marine life",
      slug: "great-barrier-reef-snorkeling",
      checked: false,
    },
    {
      title: "Barcelona Architecture Tour",
      location: "Barcelona, Spain",
      description: "Discover the unique architectural wonders of Antoni Gaudí",
      slug: "barcelona-architecture-tour",
      checked: false,
    },
    {
      title: "Serengeti Balloon Safari",
      location: "Serengeti, Tanzania",
      description: "Enjoy a breathtaking hot air balloon ride over the Serengeti plains",
      slug: "serengeti-balloon-safari",
      checked: false,
    },
    {
      title: "Dubai Skyline Tour",
      location: "Dubai, UAE",
      description: "Take a tour of Dubai's iconic skyscrapers and modern architecture",
      slug: "dubai-skyline-tour",
      checked: false,
    },
    {
      title: "Blue Lagoon Iceland",
      location: "Grindavík, Iceland",
      description: "Relax in the geothermal spa waters of the Blue Lagoon",
      slug: "blue-lagoon-iceland",
      checked: false,
    },
    {
      title: "Masai Mara Hot Air Balloon",
      location: "Maasai Mara, Kenya",
      description: "Experience wildlife viewing from a hot air balloon in Maasai Mara",
      slug: "masai-mara-hot-air-balloon",
      checked: false,
    },
    {
      title: "Victoria Falls Tour",
      location: "Victoria Falls, Zambia/Zimbabwe",
      description: "Marvel at the majestic Victoria Falls, one of the Seven Natural Wonders",
      slug: "victoria-falls-tour",
      checked: false,
    },
    {
      title: "Bora Bora Overwater Bungalow",
      location: "Bora Bora, French Polynesia",
      description: "Stay in an overwater bungalow and enjoy crystal-clear waters",
      slug: "bora-bora-overwater-bungalow",
      checked: false,
    },
    {
      title: "Sahara Desert Camel Trek",
      location: "Sahara Desert, Morocco",
      description: "Embark on a camel trek across the vast Sahara Desert",
      slug: "sahara-desert-camel-trek",
      checked: false,
    },
    {
      title: "Iguazu Falls Visit",
      location: "Iguazu Falls, Argentina/Brazil",
      description: "Explore the breathtaking Iguazu Falls from both Argentine and Brazilian sides",
      slug: "iguazu-falls-visit",
      checked: false,
    },
    {
      title: "Antarctica Expedition",
      location: "Antarctica",
      description: "Join an expedition to the icy continent and witness its pristine landscapes",
      slug: "antarctica-expedition",
      checked: false,
    },
    {
      title: "Lisbon Tram 28 Ride",
      location: "Lisbon, Portugal",
      description: "Ride the historic Tram 28 through Lisbon's charming neighborhoods",
      slug: "lisbon-tram-28-ride",
      checked: false,
    },
    {
      title: "New York City Broadway Show",
      location: "New York City, USA",
      description: "Attend a world-class Broadway theatrical performance",
      slug: "nyc-broadway-show",
      checked: false,
    },
    {
      title: "Moscow Red Square Tour",
      location: "Moscow, Russia",
      description: "Tour the historic Red Square and its iconic landmarks",
      slug: "moscow-red-square-tour",
      checked: false,
    },
    {
      title: "Cappadocia Cave Hotel Stay",
      location: "Cappadocia, Turkey",
      description: "Stay in a unique cave hotel nestled in the fairy chimneys of Cappadocia",
      slug: "cappadocia-cave-hotel-stay",
      checked: false,
    },
    {
      title: "Petra Night Visit",
      location: "Petra, Jordan",
      description: "Experience the magical Petra by night, illuminated by candles",
      slug: "petra-night-visit",
      checked: false,
    },
    {
      title: "Reykjavik Northern Lights Tour",
      location: "Reykjavik, Iceland",
      description: "Join a guided tour to witness the Northern Lights from Reykjavik",
      slug: "reykjavik-northern-lights-tour",
      checked: false,
    },
    {
      title: "Kyoto Tea Ceremony",
      location: "Kyoto, Japan",
      description: "Participate in a traditional Japanese tea ceremony in Kyoto",
      slug: "kyoto-tea-ceremony",
      checked: false,
    },
    {
      title: "Mount Kilimanjaro Climb",
      location: "Tanzania",
      description: "Climb Africa's highest peak, Mount Kilimanjaro",
      slug: "mount-kilimanjaro-climb",
      checked: false,
    },
    {
      title: "Venice Carnival Participation",
      location: "Venice, Italy",
      description: "Experience the vibrant and masked festivities of the Venice Carnival",
      slug: "venice-carnival-participation",
      checked: false,
    },
    {
      title: "Banff Lake Louise Kayaking",
      location: "Lake Louise, Canada",
      description: "Kayak on the serene waters of Lake Louise surrounded by mountains",
      slug: "banff-lake-louise-kayaking",
      checked: false,
    },
    {
      title: "Prague Old Town Exploration",
      location: "Prague, Czech Republic",
      description: "Stroll through the historic Old Town of Prague with its stunning architecture",
      slug: "prague-old-town-exploration",
      checked: false,
    },
    {
      title: "Singapore Gardens Visit",
      location: "Singapore",
      description: "Explore the futuristic Gardens by the Bay and Singapore Botanic Gardens",
      slug: "singapore-gardens-visit",
      checked: false,
    },
    {
      title: "Mount Everest Base Camp Trek",
      location: "Nepal",
      description: "Trek to the base camp of the world's highest mountain, Mount Everest",
      slug: "everest-base-camp-trek",
      checked: false,
    },
    {
      title: "Iceland Ring Road Journey",
      location: "Iceland",
      description: "Drive the entire Ring Road to experience Iceland's diverse landscapes",
      slug: "iceland-ring-road-journey",
      checked: false,
    },
    {
      title: "Great Barrier Reef Sailing",
      location: "Queensland, Australia",
      description: "Sail through the Great Barrier Reef and explore its marine biodiversity",
      slug: "great-barrier-reef-sailing",
      checked: false,
    },
    {
      title: "Santorini Wine Tasting",
      location: "Santorini, Greece",
      description: "Taste exquisite wines in the vineyards of Santorini",
      slug: "santorini-wine-tasting",
      checked: false,
    },
    {
      title: "Yellowstone Geyser Watching",
      location: "Yellowstone National Park, USA",
      description: "Observe the erupting geysers and geothermal features of Yellowstone",
      slug: "yellowstone-geyser-watching",
      checked: false,
    },
    {
      title: "Sahara Desert Stargazing",
      location: "Sahara Desert, Morocco",
      description: "Enjoy a night under the stars in the vast Sahara Desert",
      slug: "sahara-desert-stargazing",
      checked: false,
    },
    {
      title: "Great Ocean Road Sunrise",
      location: "Great Ocean Road, Australia",
      description: "Watch a stunning sunrise while driving along the Great Ocean Road",
      slug: "great-ocean-road-sunrise",
      checked: false,
    },
    {
      title: "Kyoto Bamboo Forest Walk",
      location: "Kyoto, Japan",
      description: "Walk through the serene bamboo groves of Arashiyama",
      slug: "kyoto-bamboo-forest-walk",
      checked: false,
    },
    {
      title: "Lisbon Oceanarium Visit",
      location: "Lisbon, Portugal",
      description: "Explore one of the largest indoor aquariums in Europe",
      slug: "lisbon-oceanarium-visit",
      checked: false,
    },
    {
      title: "Mount Rushmore Tour",
      location: "South Dakota, USA",
      description: "Visit the iconic Mount Rushmore National Memorial",
      slug: "mount-rushmore-tour",
      checked: false,
    },
    {
      title: "Great Barrier Reef Conservation Tour",
      location: "Queensland, Australia",
      description: "Participate in conservation efforts to protect the Great Barrier Reef",
      slug: "great-barrier-reef-conservation-tour",
      checked: false,
    },
    {
      title: "Amazon Rainforest Expedition",
      location: "Brazil",
      description: "Explore the biodiversity of the Amazon Rainforest",
      slug: "amazon-rainforest-expedition",
      checked: false,
    },
    {
      title: "Cairo Pyramids Visit",
      location: "Cairo, Egypt",
      description: "Explore the ancient pyramids and the Great Sphinx of Giza",
      slug: "cairo-pyramids-visit",
      checked: false,
    },
    {
      title: "Phuket Island Hopping",
      location: "Phuket, Thailand",
      description: "Hop between the stunning islands around Phuket",
      slug: "phuket-island-hopping",
      checked: false,
    },
    {
      title: "Galápagos Wildlife Tour",
      location: "Galápagos Islands, Ecuador",
      description: "Observe unique wildlife species in their natural habitats",
      slug: "galapagos-wildlife-tour",
      checked: false,
    },
    {
      title: "Kyoto Imperial Palace Tour",
      location: "Kyoto, Japan",
      description: "Tour the historic Imperial Palace and its beautiful gardens",
      slug: "kyoto-imperial-palace-tour",
      checked: false,
    },
    {
      title: "Bali Rice Terraces Visit",
      location: "Bali, Indonesia",
      description: "Walk through the iconic rice terraces of Bali's Ubud region",
      slug: "bali-rice-terraces-visit",
      checked: false,
    },
    {
      title: "Amsterdam Canal Cruise",
      location: "Amsterdam, Netherlands",
      description: "Cruise through Amsterdam's historic canals and enjoy the city views",
      slug: "amsterdam-canal-cruise",
      checked: false,
    },
    {
      title: "Iceland Glacier Hiking",
      location: "Vatnajökull, Iceland",
      description: "Hike across Iceland's largest glacier and witness its icy landscapes",
      slug: "iceland-glacier-hiking",
      checked: false,
    },
    {
      title: "Sydney Harbour Bridge Climb",
      location: "Sydney, Australia",
      description: "Climb the Sydney Harbour Bridge for panoramic views of the city",
      slug: "sydney-harbour-bridge-climb",
      checked: false,
    },
    {
      title: "Banff Wildlife Safari",
      location: "Banff National Park, Canada",
      description: "Spot diverse wildlife species during a safari in Banff",
      slug: "banff-wildlife-safari",
      checked: false,
    },
    {
      title: "Barcelona La Sagrada Familia Tour",
      location: "Barcelona, Spain",
      description: "Tour the unfinished masterpiece of Antoni Gaudí, La Sagrada Familia",
      slug: "la-sagrada-familia-tour",
      checked: false,
    },
    {
      title: "Hawaii Volcanoes National Park",
      location: "Hawaii, USA",
      description: "Explore active volcanic landscapes and unique ecosystems",
      slug: "hawaii-volcanoes-national-park",
      checked: false,
    },
    {
      title: "Santorini Boat Tour",
      location: "Santorini, Greece",
      description: "Take a boat tour around Santorini's caldera and volcanic islands",
      slug: "santorini-boat-tour",
      checked: false,
    },
    {
      title: "Perth Pinnacles Desert Tour",
      location: "Perth, Australia",
      description: "Visit the otherworldly Pinnacles Desert formations",
      slug: "perth-pinnacles-desert-tour",
      checked: false,
    },
    {
      title: "Kyoto Night Illumination",
      location: "Kyoto, Japan",
      description: "Enjoy the enchanting night illuminations at Kyoto's temples and gardens",
      slug: "kyoto-night-illumination",
      checked: false,
    },
    {
      title: "Los Angeles Hollywood Tour",
      location: "Los Angeles, USA",
      description: "Tour Hollywood landmarks and visit famous movie studios",
      slug: "los-angeles-hollywood-tour",
      checked: false,
    },
    {
      title: "Iceland Blue Lagoon Spa",
      location: "Reykjavik, Iceland",
      description: "Relax in the geothermal waters of the Blue Lagoon Spa",
      slug: "iceland-blue-lagoon-spa",
      checked: false,
    },
    {
      title: "Rome Colosseum Tour",
      location: "Rome, Italy",
      description: "Explore the ancient Colosseum and learn about its history",
      slug: "rome-colosseum-tour",
      checked: false,
    },
    {
      title: "Dubrovnik Old Town Walk",
      location: "Dubrovnik, Croatia",
      description: "Walk through the historic walls and streets of Dubrovnik's Old Town",
      slug: "dubrovnik-old-town-walk",
      checked: false,
    },
    {
      title: "Maldives Overwater Villa Stay",
      location: "Maldives",
      description: "Stay in a luxurious overwater villa with direct access to the ocean",
      slug: "maldives-overwater-villa-stay",
      checked: false,
    },
    {
      title: "Swiss Glacier Express Train",
      location: "Switzerland",
      description: "Ride the scenic Glacier Express train through the Swiss Alps",
      slug: "swiss-glacier-express-train",
      checked: false,
    },
    {
      title: "Great Wall Marathon Participation",
      location: "Beijing, China",
      description: "Participate in the annual marathon along the Great Wall of China",
      slug: "great-wall-marathon-participation",
      checked: false,
    },
    {
      title: "Salar de Uyuni Salt Flats",
      location: "Uyuni, Bolivia",
      description: "Drive across the world's largest salt flat and capture stunning reflections",
      slug: "salar-de-uyuni-salt-flats",
      checked: false,
    },
    {
      title: "Banff Lake Louise Canoeing",
      location: "Lake Louise, Canada",
      description: "Canoe on the turquoise waters of Lake Louise surrounded by mountains",
      slug: "lake-louise-canoeing",
      checked: false,
    },
    {
      title: "Victoria Peak Tram Ride",
      location: "Hong Kong",
      description: "Take the historic tram to Victoria Peak for panoramic city views",
      slug: "victoria-peak-tram-ride",
      checked: false,
    },
    {
      title: "Bora Bora Scuba Diving",
      location: "Bora Bora, French Polynesia",
      description: "Dive into the crystal-clear waters of Bora Bora's coral reefs",
      slug: "bora-bora-scuba-diving",
      checked: false,
    },
    {
      title: "Lisbon Fado Music Night",
      location: "Lisbon, Portugal",
      description: "Experience traditional Fado music in a cozy Lisbon venue",
      slug: "lisbon-fado-music-night",
      checked: false,
    },
    {
      title: "Yellowstone Wildlife Watching",
      location: "Yellowstone National Park, USA",
      description: "Observe diverse wildlife including bison, elk, and wolves in Yellowstone",
      slug: "yellowstone-wildlife-watching",
      checked: false,
    },
    {
      title: "Amsterdam Tulip Festival",
      location: "Amsterdam, Netherlands",
      description: "Visit the vibrant tulip fields during the annual Tulip Festival",
      slug: "amsterdam-tulip-festival",
      checked: false,
    },
    {
      title: "Dubai Mall Aquarium Visit",
      location: "Dubai, UAE",
      description: "Explore the massive aquarium within the Dubai Mall",
      slug: "dubai-mall-aquarium-visit",
      checked: false,
    },
    {
      title: "Great Barrier Reef Sailing Adventure",
      location: "Queensland, Australia",
      description: "Sail through the Great Barrier Reef and explore its marine life",
      slug: "great-barrier-reef-sailing-adventure",
      checked: false,
    },
    {
      title: "Prague Castle Tour",
      location: "Prague, Czech Republic",
      description: "Tour the historic Prague Castle and its beautiful grounds",
      slug: "prague-castle-tour",
      checked: false,
    },
    {
      title: "Maui Road to Hana Drive",
      location: "Maui, Hawaii, USA",
      description: "Drive the scenic Road to Hana with waterfalls and lush landscapes",
      slug: "maui-road-to-hana-drive",
      checked: false,
    },
    {
      title: "Singapore Marina Bay Sands SkyPark",
      location: "Singapore",
      description: "Visit the SkyPark for stunning views of Singapore's skyline",
      slug: "marina-bay-sands-sky-park",
      checked: false,
    },
    {
      title: "Barcelona Beach Day",
      location: "Barcelona, Spain",
      description: "Relax on Barcelona's vibrant beaches and enjoy the Mediterranean sun",
      slug: "barcelona-beach-day",
      checked: false,
    },
    {
      title: "Rock of Gibraltar Visit",
      location: "Gibraltar",
      description: "Explore the historic Rock of Gibraltar and its unique wildlife",
      slug: "rock-of-gibraltar-visit",
      checked: false,
    },
    {
      title: "Kyoto Gion District Stroll",
      location: "Kyoto, Japan",
      description: "Stroll through the traditional Gion district, home to geishas",
      slug: "kyoto-gion-district-stroll",
      checked: false,
    },
    {
      title: "Paris Seine River Cruise",
      location: "Paris, France",
      description: "Enjoy a romantic cruise along the Seine River with views of iconic landmarks",
      slug: "paris-seine-river-cruise",
      checked: false,
    },
    {
      title: "Swiss Chocolate Tour",
      location: "Switzerland",
      description: "Indulge in a chocolate tour across Switzerland's renowned chocolatiers",
      slug: "swiss-chocolate-tour",
      checked: false,
    },
    {
      title: "Iceland Golden Circle Tour",
      location: "Iceland",
      description: "Visit Thingvellir, Geysir, and Gullfoss on the Golden Circle route",
      slug: "iceland-golden-circle-tour",
      checked: false,
    },
    {
      title: "Venice Gondola Serenade",
      location: "Venice, Italy",
      description: "Enjoy a serenade while cruising the canals on a gondola",
      slug: "venice-gondola-serenade",
      checked: false,
    },
    {
      title: "Grand Teton National Park Hiking",
      location: "Wyoming, USA",
      description: "Hike through the breathtaking trails of Grand Teton National Park",
      slug: "grand-teton-national-park-hiking",
      checked: false,
    },
    {
      title: "Santorini Volcanic Island Tour",
      location: "Santorini, Greece",
      description: "Tour the volcanic islands and hot springs around Santorini",
      slug: "santorini-volcanic-island-tour",
      checked: false,
    },
    {
      title: "Bali Ubud Monkey Forest",
      location: "Ubud, Bali, Indonesia",
      description: "Visit the sacred Monkey Forest and interact with its playful inhabitants",
      slug: "bali-ubud-monkey-forest",
      checked: false,
    },
    {
      title: "Paris Montmartre Art Tour",
      location: "Paris, France",
      description: "Explore the artistic Montmartre district and its historic art studios",
      slug: "paris-montmartre-art-tour",
      checked: false,
    },
    {
      title: "Kyoto Fushimi Inari Shrine",
      location: "Kyoto, Japan",
      description: "Walk through the thousands of red torii gates at Fushimi Inari Shrine",
      slug: "kyoto-fushimi-inari-shrine",
      checked: false,
    },
    {
      title: "Cappadocia Underground City",
      location: "Cappadocia, Turkey",
      description: "Explore the ancient underground cities carved into soft rock",
      slug: "cappadocia-underground-city",
      checked: false,
    },
    {
      title: "Great Barrier Reef Glass Bottom Boat Tour",
      location: "Queensland, Australia",
      description: "View the vibrant coral reefs and marine life from a glass-bottom boat",
      slug: "great-barrier-reef-glass-bottom-boat-tour",
      checked: false,
    },
    {
      title: "Kyoto Kinkaku-ji (Golden Pavilion)",
      location: "Kyoto, Japan",
      description: "Visit the stunning Golden Pavilion set amidst beautiful gardens",
      slug: "kyoto-kinkaku-ji-golden-pavilion",
      checked: false,
    },
    {
      title: "Tokyo Shibuya Crossing Experience",
      location: "Tokyo, Japan",
      description: "Experience the bustling Shibuya Crossing, one of the busiest intersections in the world",
      slug: "tokyo-shibuya-crossing-experience",
      checked: false,
    },
    {
      title: "Great Barrier Reef Helicopter Tour",
      location: "Queensland, Australia",
      description: "See the Great Barrier Reef from above on a thrilling helicopter tour",
      slug: "great-barrier-reef-helicopter-tour",
      checked: false,
    },
    {
      title: "Kyoto Ginkaku-ji (Silver Pavilion)",
      location: "Kyoto, Japan",
      description: "Explore the serene Silver Pavilion and its surrounding gardens",
      slug: "kyoto-ginkaku-ji-silver-pavilion",
      checked: false,
    },
  ];
  