// src/app/utils/countryMapping.js

export const countryToISO = {
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Argentina': 'ARG',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Belgium': 'BEL',
    'Brazil': 'BRA',
    'Canada': 'CAN',
    'China': 'CHN',
    'Denmark': 'DNK',
    'Egypt': 'EGY',
    'Finland': 'FIN',
    'France': 'FRA',
    'Germany': 'DEU',
    'Greece': 'GRC',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Mexico': 'MEX',
    'Netherlands': 'NLD',
    'New Zealand': 'NZL',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Russia': 'RUS',
    'South Africa': 'ZAF',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Thailand': 'THA',
    'Turkey': 'TUR',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    'USA': 'USA',
    'Vietnam': 'VNM',
    'Guatemala': 'GTM',
    'Saint Barthélemy': 'BLM',
    'Slovakia': 'SVK',
    'Croatia': 'HRV',
    'Uruguay': 'URY',
    'Bosnia and Herzegovina': 'BIH',
    'Montenegro': 'MNE',
    'Chile': 'CHL',
    'Mauritius': 'MUS',
    'Botswana': 'BWA',
    'Vatican City': 'VAT',
    'Singapore': 'SGP',
    'Estonia': 'EST',
    'Slovenia': 'SVN',  
    'Czech Republic': 'CZE',
    'Monaco': 'MCO',
    'Seychelles': 'SYC'

  };